"""Step 4A — Deterministic, non-AI regex index parser (PASS route).

Sweeps the tagged text left-to-right with a compiled pattern. On every open
tag it records the label and the current length of the progressively-built
clean string (the ``start`` offset); on the matching close tag it records the
``end`` offset and slices the literal inner text. Because the offsets are
*counted* mathematically rather than generated by a model, this bypasses the
off-by-one / sub-token index drift typical of generative coordinate emission.

Offsets are 0-based and half-open: ``clean_text[start:end] == span.text``.
"""
from __future__ import annotations

import re
from typing import List, Tuple

from . import TAGSET
from .schemas import Span

# Matches an opening <LABEL> or closing </LABEL> tag for any known label.
_TAG_RE = re.compile(r"<(/?)(" + "|".join(TAGSET) + r")>")


class TagParseError(ValueError):
    """Raised when tag structure is malformed (unbalanced / mismatched / nested)."""


def strip_tags(tagged_text: str) -> str:
    """Return the clean text with all known tags removed (no offset tracking)."""
    return _TAG_RE.sub("", tagged_text)


def parse_tagged_text(tagged_text: str) -> Tuple[str, List[Span]]:
    """Parse inline-tagged text into ``(clean_text, spans)``.

    Raises ``TagParseError`` on unbalanced or mismatched tags so the orchestrator
    can route the row to human review instead of committing bad coordinates.
    """
    clean_parts: List[str] = []
    clean_len = 0
    spans: List[Span] = []
    stack: List[Tuple[str, int]] = []  # (label, start_offset)
    cursor = 0

    for m in _TAG_RE.finditer(tagged_text):
        # Literal text since the previous tag boundary contributes to clean text.
        chunk = tagged_text[cursor:m.start()]
        if chunk:
            clean_parts.append(chunk)
            clean_len += len(chunk)
        cursor = m.end()

        is_close = m.group(1) == "/"
        label = m.group(2)

        if not is_close:
            stack.append((label, clean_len))
        else:
            if not stack:
                raise TagParseError(f"Closing </{label}> with no matching open tag")
            open_label, start = stack.pop()
            if open_label != label:
                raise TagParseError(
                    f"Tag mismatch: <{open_label}> closed by </{label}>"
                )
            spans.append(
                Span(label=label, text="", start=start, end=clean_len)
            )

    # Trailing literal text after the last tag.
    trailing = tagged_text[cursor:]
    if trailing:
        clean_parts.append(trailing)

    if stack:
        unclosed = ", ".join(f"<{lbl}>" for lbl, _ in stack)
        raise TagParseError(f"Unclosed tag(s): {unclosed}")

    clean_text = "".join(clean_parts)

    # Fill in the literal span text now that clean_text is complete, and order
    # spans by their start offset (finditer pops them in close-tag order).
    for span in spans:
        span.text = clean_text[span.start:span.end]
    spans.sort(key=lambda s: (s.start, s.end))

    return clean_text, spans


def parse_and_verify(tagged_text: str, raw_text: str) -> List[Span]:
    """Parse tags and enforce the character-preservation invariant.

    Raises ``TagParseError`` if the stripped tagged text does not match the
    pristine raw text exactly (a defensive backstop even when the auditor
    returned PASS — see PRD §3 decision-fork).
    """
    clean_text, spans = parse_tagged_text(tagged_text)
    if clean_text != raw_text:
        raise TagParseError(
            "Character-preservation invariant violated: "
            "strip_tags(tagged) != raw_text"
        )
    return spans
